#43 Updated Search contacts
Landry333/Big-Owl pull request #128
Opened 2020-11-03 04:47 UTC by KennanHoa

- check if users already in database.
* Contact requires the country code (i.e +1)

2020-11-04 02:59 UTC, refatK commented
Please link the issue in you commit next time btw

2020-11-04 03:53 UTC, refatK commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
Could you explain what this does?

2020-11-04 03:54 UTC, refatK commented on app/src/main/java/com/example/bigowlapp/SearchContactsToSupervise.java
> +                //Log.d("12345", number.replaceFirst(".+?\\+","+").replaceAll("[^+0-9]",""));
You should probably remove these logs.

2020-11-04 04:00 UTC, refatK reviewed
I tried the application and it seems to works, although i'm not sure it was the expected result.

When I clicked on a contact without a number match the app would pop up a toast sayin the user already exists.

If the number exactly matched the number in the db, then it went to the sms invitation page.

* Is the number supposed to be auto filled when it swaps to sms invitation page, or must the user manually enter the number themself?

* In contacts the number might be something like `12345671234` and in db it could be `+12345671234`. I was assuming it would say it exists, but it said the umber didn't exist. Was that expected?

2020-11-04 04:02 UTC, refatK commented on app/src/main/java/com/example/bigowlapp/SearchContactsToSupervise.java
> +            {
please reformat this file to use same style as everyone else.

You can do this in Android studio using the command `CTRL+ALT+SHIFT+L`, and selecting reformat code

2020-11-04 05:05 UTC, KhangZhengNg requested changes
Many files are in com.example.bigowlapp which is totally wrong. Please update the branch from staging and put the files in proper directory after com.example.bigowlapp. Check and remove code instead of commenting them out if they are useless. Also consider replacing listener with new method with lambda (suggestions from yellow light bulb)

2020-11-05 08:04 UTC, refatK approved these changes
Thanks for doing the changes I asked for. Approved!

2020-11-06 02:49 UTC, KhangZhengNg approved these changes
Thanks for sticking with the project's folder structure. Good job!

2020-11-06 02:49 UTC, KhangZhengNg commented on app/src/main/java/com/example/bigowlapp/activity/SearchContactsToSupervise.java
> +                        .addOnCompleteListener(new OnCompleteListener<QuerySnapshot>() {
Nice and clean way to do query in FirebaseFirestore!

2020-11-06 18:04 UTC, darkheros12 requested changes
Please, before merging, pull from staging to avoid any inconvenient. I will approve it once it is one.

2020-11-07 05:10 UTC, merged