#119 add default group
Landry333/Big-Owl pull request #132
Opened 2020-11-04 04:36 UTC by refatK

#119 

**Description**
When you sign up, a group should be added to the db for the new user.

**How to test**
Sign up a user and check that in firebase that a group was added with a MonitoringId that matches the Id of the usr added

2020-11-04 05:43 UTC, KhangZhengNg requested changes
Tried signing up multiple times. Only see myself on Firebase Authentication, but nothing happend to collection "users" and "groups" in Cloud Firestore. Please ensure that once an account is created, a "user" document and a "group" document are also created properly in Cloud Firestore.

2020-11-05 06:48 UTC, KhangZhengNg approved these changes

2020-11-05 06:48 UTC, KhangZhengNg commented on app/src/main/java/com/example/bigowlapp/model/Group.java
> +        return (supervisedUserId == null) ? new ArrayList<>() : supervisedUserId;
Great! Now an empty array will be created and inserted in "supervisedUserId" field within the proper "group" document on Cloud Firestore when an user first create an account and get a new monitoring group.

2020-11-06 05:07 UTC, ggebran approved these changes
The application is working as expected and the code is well documented. Approved.

2020-11-06 05:14 UTC, merged