#65 code quality
Landry333/Big-Owl pull request #156
Opened 2020-11-09 20:08 UTC by refatK

NOTE: don't merge yet

Adding code quality analysis tools to our app. I added:

- **Sonarcloud**: catches code smells. Link: https://sonarcloud.io/dashboard?id=Landry333_Big-Owl
- **ReviewDog**: will give warnings from AndroidLint directly on our PRs. Should help keeping things clean

I added an issue in this commit that should have been caught:
https://github.com/Landry333/Big-Owl/commit/e263b33eee9bd8c28ccfe098b732dc82f63fa8ac

Should also be shown on PR:

![image](https://user-images.githubusercontent.com/31963426/98590657-23288500-229d-11eb-9fde-4fc18c4a97f3.png)

2020-11-09 21:24 UTC, refatK commented
Reviewdog provides 3 types of reporter. Which should we use? We can also set different ones depending on the action:

1. [GitHub Checks (-reporter=github-pr-check)](https://github.com/reviewdog/reviewdog#reporter-github-checks--reportergithub-pr-check) (I think this only checks the changes within the PR) ([example](https://github.com/reviewdog/reviewdog/pull/275/files#annotation_6177941961779419))

2. [GitHub Checks (-reporter=github-check)](https://github.com/reviewdog/reviewdog#reporter-github-checks--reportergithub-check) (currently set, shows all problems in code as of commit) ([example](https://github.com/reviewdog/reviewdog/pull/364/files) [also the current state of the PR at this point of time]) (we can also setup a [badge](https://github.com/reviewdog/reviewdog#reviewdog-badge-) with this one)


3. [GitHub PullRequest review comment (-reporter=github-pr-review)](https://github.com/reviewdog/reviewdog#reporter-github-pullrequest-review-comment--reportergithub-pr-review) (will be like a PR review instead) ([example](https://github.com/reviewdog/reviewdog/pull/24/files))


Which ones should we use. We can even use multiple based on what we are doing (ex: only do on staging merge, only on PR, ...)

Also I currently set it to be warning only. The CI will not fail the PR, it only warns you about the lint issues.\!

2020-11-09 22:16 UTC, ShawnGuerra-Bautista requested changes
All the configuration looks good. Good job.

I know you already stated this in the code's comments, but just remember to remove the example that you provided for the lint.

2020-11-09 22:16 UTC, ShawnGuerra-Bautista commented on build.gradle
> +        // Do not update the build version (keep: classpath 'com.android.tools.build:gradle:4.0.2')
Does this enforce that this dependency must be present?

Also, if let's say we add 
`classpath 'com.android.tools.build:gradle:6.1.1'`
and we don't remove 4.0.2, does Gradle complain?

2020-11-09 22:16 UTC, ShawnGuerra-Bautista commented on app/src/main/res/values/strings.xml
> +    <string name="unused_resource_for_review_dog_check_test">Hopefully reviewdog calls this out. Will be removed!</string>
Cool the lint does work and show bad code!

You can remove it.

2020-11-11 05:06 UTC, refatK commented
Seems like Sonarcloud sets up reports for the changes within the branch too. Good stuff.

2020-11-11 06:34 UTC, KhangZhengNg approved these changes
This is totally awesome! thanks for adding it to our project!

2020-11-15 02:23 UTC, ShawnGuerra-Bautista approved these changes

2020-11-15 23:31 UTC, merged