#160 Abstract the model, improve structure of repository classes, improve overall code quality, and add tests to existing code.
Landry333/Big-Owl pull request #203
Opened 2021-01-29 22:49 UTC by refatK

### Related Issues
Closes #160

### Description
This is refactor PR in which we changed the structure or the Model and ViewModel classes to instead use a base Parent class. Using this, we have used inheritance to further abstract these objects and have reduced coupling in the proccess. Further details can be found in the issue description.

### How to check PR
- This is a non-functional PR, therefore all that is needed is to check the app is working as it always has been, and that all behavior has been preserved. The bulk of reviewing should be focused on the code itself.

2021-01-29 23:42 UTC, KhangZhengNg requested changes
Overall, good refactoring, reformatting, and testing. Good job on adding base view model class, and let all view models to extend it. Also, nice work on adding MVC to early-stage activities. There are still 7 Code Smells to be fixed.

2021-01-29 23:55 UTC, ShawnGuerra-Bautista commented
> Overall, good refactoring, reformatting, and testing. Good job on adding base view model class, and let all view models to extend it. Also, nice work on adding MVC to early-stage activities. There are still 7 Code Smells to be fixed.

@KhangZhengNg We checked those code smells, and there are ones that we can't change unfortunately.

We removed the dead code one, so that's a nice catch.

However, most of them are the TODOs in the code which we can't really take them out because they are tasks to be done in the future (and these are beyond the scope of this issue). The other thing is to change the package name to follow a specific format, but it will cause a lot of issues when pulling from this branch (we would need a meeting for it and warn everyone about it).

2021-01-30 00:46 UTC, KhangZhengNg approved these changes

2021-01-30 00:50 UTC, Landry333 approved these changes
The facade design pattern seems well implemented all over the code, good code clean up and renaming. I tested the app and it is working well. I approve the changes

2021-01-30 00:55 UTC, merged