#38 confirmation of created schedule
Landry333/Big-Owl pull request #239
Opened 2021-03-03 04:39 UTC by KennanHoa

#38 

**Description**
- Confirmation screen when creating a schedule with all the selected information for the schedule.
- User can cancel to modify the data or confirm to create the new schedule.

**How to check**
- Create a new schedule and see if the confirmation screen pops up.

2021-03-06 22:34 UTC, refatK requested changes
![image](https://user-images.githubusercontent.com/31963426/110222697-283fbe80-7ea2-11eb-83fd-da5af0e9b9dc.png)

A test broke due to the change to the form, so the test will have to be fixed. Shouldn't be too complicated.

2021-03-10 03:14 UTC, ShawnGuerra-Bautista requested changes
Feature works well.

The only problem is that a test for setting schedule is failing, and should be fixed.

2021-03-11 23:28 UTC, refatK commented
Code and functionality is good, so just the test needs to be fixed and the branch updated, and it should be good to merge.

2021-03-11 23:32 UTC, refatK commented on app/src/main/java/com/example/bigowlapp/model/Schedule.java
> +    }
Is this needed?

2021-03-11 23:35 UTC, refatK commented on app/src/main/java/com/example/bigowlapp/fragments/ScheduleFormFragment.java
> +        });
Can do convert these to lambda calls instead.

2021-03-18 10:09 UTC, KennanHoa commented on app/src/main/java/com/example/bigowlapp/model/Schedule.java
> +    }
removed

2021-03-18 22:43 UTC, KhangZhengNg approved these changes
Good job adding the confirmation step and the testing file

2021-03-25 00:36 UTC, refatK approved these changes
Feature works, and you addressed my changes, so good jib and approving!

2021-03-25 00:36 UTC, refatK commented on app/src/androidTest/java/com/example/bigowlapp/fragments/ScheduleFormFragmentTest.java
> +        onView(withText("CONFIRM")).perform(click());
Nice job integrating your additions to the test, both fixing it and increasing coverage a bit

2021-03-25 00:36 UTC, refatK commented on app/src/main/java/com/example/bigowlapp/fragments/ScheduleFormFragment.java
> +        String selectedLocation = (location.placeName() == null) ? location.address() : location.placeName();
Nice, good style fix

2021-03-25 00:37 UTC, ShawnGuerra-Bautista approved these changes

2021-03-25 02:41 UTC, merged