Remove #285294 Color from non clickable sections (UI updates after usability test 1)
Landry333/Big-Owl pull request #249
Opened 2021-03-19 21:55 UTC by SeifElDerby

The Color #285294 was reoved from the Logo.png file to remove excess #285294 usage in non clickable areas for a better understanding of clickable areas and non clickable areas for all users.

### Related Issues
<list issues here that the PR is connected to: ex: #21>

### Description
<describe what you did in the PR>

### How to check PR
<describe what reviewers need to do to check that the PR is working>
<Note: List most important files in the PR>

2021-03-31 14:18 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="?attr/white" />
This parameter value can not be found during the build and will fail the build. You can just leave the original value unchanged

2021-03-31 14:19 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
Same as above, this parameter value will give the background the same color as the icon, therefore making it to be invisible. You can just leave it as unchanged

2021-03-31 14:22 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
Same as above, this will make the icon to be invisible because of same color with background. You can just leave it as unchanged

2021-03-31 14:23 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
Same issue here, this will make the icon to be invisible because of same color with background. Just leave it as unchanged

2021-03-31 14:25 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
This parameter value will make the background to be blue whereas the other icons background are white. To have the same white color for all  icons background you should leave it as unchanged

2021-03-31 14:47 UTC, Landry333 requested changes
As your PR wasn't to change the top application bar, you should leave the app_bar.xml file unchanged. Apart of that, the PR should be ok

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
Same as above, this parameter value will give the background the same color as the icon, therefore making it to be invisible. You can just leave it as unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
This parameter should not be changed, as it will give the background the same color as the icon, therefore making it to be invisible

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="?attr/white" />
This parameter value can not be found during the build and will fail the build. You can just leave the original value unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="?attr/white" />
Same as above, this parameter value can not be found during the build and will fail the build.  Just leave the original value unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="?attr/white" />
Same issue here, the parameter value can not be found during the build and will fail the build.  Just leave the original value unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="?attr/white" />
Same as above, this parameter value can not be found during the build and will fail the build.  You should leave the original value unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +        android:background="?attr/white" />
Same issue as above, this parameter value can not be found during the build and will fail the build.  Just leave the original value unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
This parameter value will make the background to be blue whereas the other icons background are white. To have the same white color for all icons background you should leave it as unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
Same issue here, this will make the icon to be invisible because of same color with background. Just leave it as unchanged

2021-03-31 14:47 UTC, Landry333 commented on app/src/main/res/layout/app_bar.xml
> +            android:background="@color/colorPrimary"
Same as above, this will make the icon to be invisible because of same color with background. You can just leave it as unchanged

2021-03-31 23:59 UTC, ShawnGuerra-Bautista requested changes

2021-03-31 23:59 UTC, ShawnGuerra-Bautista commented on app/src/main/res/drawable/ic_location_marker.xml
>        android:pathData="M228.239,397.518l8.683,17.365c3.627,7.232 11.008,11.797 19.093,11.797s15.467,-4.565 19.093,-11.797l18.389,-36.779c22.379,-44.779 49.984,-88.149 76.672,-130.091l12.16,-19.136c1
These changes should be reverted.

![image](https://user-images.githubusercontent.com/23643192/113224913-75713f00-925a-11eb-8b38-efeabbab0d2a.png)

The location marker isn't a button, so it shouldn't be blue. It also looks weird in my opinion.
What should be blue are the buttons that contain the texts. You can't see it very well, but the texts such as "Select Group", and "Select Location" are buttons. Those are the UI components that should be blue.

@Landry333 What do you think?

2021-03-31 23:59 UTC, ShawnGuerra-Bautista commented on app/src/main/res/layout/app_bar.xml
> -            android:background="@color/white"
I think you should revert this whole file.

It looks very weird.

![image](https://user-images.githubusercontent.com/23643192/113225325-5de68600-925b-11eb-995d-326b41052625.png)


I reverted this file and it looks decent enough.

![image](https://user-images.githubusercontent.com/23643192/113225374-78206400-925b-11eb-919d-a5d2f59e68ba.png)

2021-04-03 20:31 UTC, ShawnGuerra-Bautista requested changes
Some changes still need to be made including changes suggested by Landry. Though, I'm not really sure what is your intention on how the UI will look like.

2021-04-03 20:31 UTC, ShawnGuerra-Bautista commented on app/src/main/res/drawable/ic_location_marker.xml
> +>>>>>>> parent of e319085 (App bar updated to have the color primary in the background)
I'm not sure what happened, but this should be fixed.

2021-04-11 04:55 UTC, Landry333 commented
This feature is no more needed as a different UI design has been chosen

2021-04-11 04:55 UTC, closed without merging