#8 #57 finishing the skeleton for monitoring & supervised group
Landry333/Big-Owl pull request #76
Opened 2020-10-14 01:36 UTC by KhangZhengNg

Create a button on homepage that directly goes into monitoring group that an user owned.
Create another button on homepage that goes to the list of groups where an user is being supervised. Clicking on the listed item will bring user to the group page.

2020-10-16 09:40 UTC, Landry333 reviewed
Your pull request didn't pass the checks. Can you fix that?

2020-10-17 04:19 UTC, refatK requested changes
Good skeleton. Need to refactor some code to remove UI-db coupling. There's some other naming issues I have mentioned which can be fixed in refactors.

The app didn't run for me though, because of the gradle version in the project-level build.gradle. I was able to run it by changing the version from 4.10 to 4.0.2

Once I made the change the app ran and I was able to see the users that are supervising me as I had expected. I'm assuming since this is just a skeleton, the visuals will be cleaned up and removal from group will be possible. Other comments I mentioned in this PR don't necessarily have to be fixed now (since they weren't made by you and don't cause the app to not run), but we should fix them eventually.


Please make these 2 changes, and then I will approve:

- [ ] Refactor Group.java to use attribute `monitoringUserId` instead of `monitorUserId`. It should match the value in the database which is `monitoringUserId`

- [ ] Change the project level build.gradle to use `classpath 'com.android.tools.build:gradle:4.0.2'` Then check that the app runs.

2020-10-18 00:04 UTC, refatK approved these changes
I made the changes that were crucial (gradle version, and Group.java inconsistency), so now I approve.

2020-10-18 03:43 UTC, Landry333 commented on app/src/main/java/com/example/bigowlapp/ViewAnotherUserActivity.java
>      @SuppressLint("SetTextI18n")
I created String variables  and passed the variables into the setText() so fix warning

2020-10-18 03:46 UTC, Landry333 commented on app/src/main/java/com/example/bigowlapp/HomeActivity.java
> +    Button btnLogOut, SendSmsInvitation, btnMonitoringGroup, btnSupervisedGroup;
I modified the name and wrote it in lowercase

2020-10-18 04:05 UTC, Landry333 approved these changes
The required changes were made, so I approve

2020-10-18 04:05 UTC, merged