moved activities to activityPage and added new field for sign up
Landry333/Big-Owl pull request #84
Opened 2020-10-19 00:08 UTC by darkheros12

2020-10-19 03:13 UTC, Landry333 requested changes
The GitHub actions checks failed. Can you fix that (only the GitHub actions checks as we will not be using Travis ci for now) ?

2020-10-19 19:11 UTC, KhangZhengNg requested changes

2020-10-19 19:11 UTC, KhangZhengNg commented on app/src/main/java/com/example/bigowlapp/ActivityPage/HomeActivity.java
> +public class HomeActivity extends AppCompatActivity {
Good job on moving files into proper folder. However, please pull new code from Staging branch as an earlier PR has been approved

2020-10-19 19:11 UTC, KhangZhengNg commented on app/src/main/java/com/example/bigowlapp/ActivityPage/SignUpActivity.java
> +                    else if(!(email.isEmpty() && pass.isEmpty() &&  userPhone.isEmpty()))
Good job on handling multiple possible inputs by a user.

2020-10-19 19:11 UTC, KhangZhengNg commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ActivityPage.SignUpActivity">
Good fix on these lines as the activity files have moved to a folder.

2020-10-19 19:59 UTC, darkheros12 commented on app/src/main/java/com/example/bigowlapp/ActivityPage/HomeActivity.java
> +public class HomeActivity extends AppCompatActivity {
DONE

2020-10-20 23:05 UTC, KhangZhengNg approved these changes
Well done on fixing things! Now the new login, signup, and home pages looks awesone!

2020-10-21 00:30 UTC, Landry333 approved these changes
The requested changes have been done. It looks ok to me

2020-10-21 00:30 UTC, merged